# Generated by Django 5.1.6 on 2025-02-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('bar_code', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('manufacturer_reference', models.CharField(max_length=64)),
            ],
        ),
    ]
